// <auto-generated />
using System;
using BlueLearnAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueLearnAPI.Migrations
{
    [DbContext(typeof(BLDbContext))]
    [Migration("20240406152158_Jugador")]
    partial class Jugador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlueLearnAPI.Model.Agricultores", b =>
                {
                    b.Property<int>("IdAgricultor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgricultor"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperacionesCultivoIdOperacion")
                        .HasColumnType("int");

                    b.HasKey("IdAgricultor");

                    b.HasIndex("OperacionesCultivoIdOperacion");

                    b.ToTable("Agricultores");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.Cultivos", b =>
                {
                    b.Property<int>("IdCultivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCultivo"));

                    b.Property<DateTime>("FechaPlantacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCampo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoCultivo")
                        .HasColumnType("int");

                    b.HasKey("IdCultivo");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.EstadoOperacion", b =>
                {
                    b.Property<int>("IdEstadoOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoOperacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstadoOperacion");

                    b.ToTable("EstadoOperacion");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJugador"));

                    b.Property<int?>("AgricultoresIdAgricultor")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("IdJugador");

                    b.HasIndex("AgricultoresIdAgricultor");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.OperacionesCultivo", b =>
                {
                    b.Property<int>("IdOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOperacion"));

                    b.Property<int?>("CultivosIdCultivo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoOperacionIdEstadoOperacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOperacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAgricultor")
                        .HasColumnType("int");

                    b.Property<int>("IdCultivo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoOperacion")
                        .HasColumnType("int");

                    b.HasKey("IdOperacion");

                    b.HasIndex("CultivosIdCultivo");

                    b.HasIndex("EstadoOperacionIdEstadoOperacion");

                    b.ToTable("OpeCultivos");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.Agricultores", b =>
                {
                    b.HasOne("BlueLearnAPI.Model.OperacionesCultivo", "OperacionesCultivo")
                        .WithMany()
                        .HasForeignKey("OperacionesCultivoIdOperacion");

                    b.Navigation("OperacionesCultivo");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.Jugador", b =>
                {
                    b.HasOne("BlueLearnAPI.Model.Agricultores", "Agricultores")
                        .WithMany()
                        .HasForeignKey("AgricultoresIdAgricultor");

                    b.Navigation("Agricultores");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.OperacionesCultivo", b =>
                {
                    b.HasOne("BlueLearnAPI.Model.Cultivos", "Cultivos")
                        .WithMany()
                        .HasForeignKey("CultivosIdCultivo");

                    b.HasOne("BlueLearnAPI.Model.EstadoOperacion", "EstadoOperacion")
                        .WithMany()
                        .HasForeignKey("EstadoOperacionIdEstadoOperacion");

                    b.Navigation("Cultivos");

                    b.Navigation("EstadoOperacion");
                });
#pragma warning restore 612, 618
        }
    }
}
