// <auto-generated />
using System;
using BlueLearnAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueLearnAPI.Migrations
{
    [DbContext(typeof(BLDbContext))]
    [Migration("20240406144243_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlueLearnAPI.Model.Cultivos", b =>
                {
                    b.Property<int>("IdCultivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCultivo"));

                    b.Property<DateTime>("FechaPlantacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCampo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoCultivo")
                        .HasColumnType("int");

                    b.HasKey("IdCultivo");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.OperacionesCultivo", b =>
                {
                    b.Property<int>("IdOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOperacion"));

                    b.Property<int?>("CultivosIdCultivo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaOperacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAgricultor")
                        .HasColumnType("int");

                    b.Property<int>("IdCultivo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoOperacion")
                        .HasColumnType("int");

                    b.HasKey("IdOperacion");

                    b.HasIndex("CultivosIdCultivo");

                    b.ToTable("OpeCu");
                });

            modelBuilder.Entity("BlueLearnAPI.Model.OperacionesCultivo", b =>
                {
                    b.HasOne("BlueLearnAPI.Model.Cultivos", "Cultivos")
                        .WithMany()
                        .HasForeignKey("CultivosIdCultivo");

                    b.Navigation("Cultivos");
                });
#pragma warning restore 612, 618
        }
    }
}
